In [1]:
import pandas as pd
import numpy as np

In [2]:
Orders = pd.read_excel('../data/raw/Muesli Project raw data.xlsx',sheet_name='Orders', header = 1)

In [3]:
Orders.head(2)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714

1- there is one None value on 'Postal Code' (dealing with missing value) = there is no matter with missing value in this column!
2- check probabitily repititive raws= there is not any repititive value
3- data type are currect: checked
4- check out of line values
5- data bining : days' name
6- turning categorical to numerical : Ship Mode

In [4]:
Orders[Orders['Postal Code'].isna()]

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
173,2235,CA-2020-104066,2020-12-05,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10001013,205.03,7,0.0,67.6599
710,9147,US-2019-165505,2019-01-23,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10002926,99.98,2,0.0,42.9914
1732,9389,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Mega Protein,OFF-AP-10000828,542.94,3,0.0,152.0232
3408,9387,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10000157,79.92,4,0.0,37.5624
3409,9388,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10001970,12.28,1,0.0,5.7716
4279,8799,US-2019-150140,2019-04-06,Standard Class,VM-21685,Valerie Mitchum,Facebook,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Only Oats,TEC-PH-10002555,1294.75,5,0.0,336.6350
4694,9390,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Power Clean Fibre Boost,OFF-EN-10001509,2.04,1,0.0,0.9588
5490,9149,US-2019-165505,2019-01-23,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Steel Cut,OFF-ST-10001526,1564.29,13,0.0,406.7154
7802,9148,US-2019-165505,2019-01-23,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Super Mega Protein,OFF-AR-10003477,8.04,6,0.0,2.7336
8415,9742,CA-2018-117086,2018-11-08,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Fruit,FUR-BO-10004834,4404.90,5,0.0,1013.1270
9693,5275,CA-2018-162887,2018-11-07,Second Class,SV-20785,Stewart Visinsky,Email,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Nuts,FUR-CH-10000595,715.20,3,0.0,178.8000

In [5]:
Orders.isna().count()

Index             9994
Order ID          9994
Order Date        9994
Ship Mode         9994
Customer ID       9994
Customer Name     9994
Origin Channel    9994
Country/Region    9994
City              9994
State             9994
Postal Code       9994
Region            9994
Category          9994
Sub-Category      9994
Product ID        9994
Sales             9994
Quantity          9994
Discount          9994
Profit            9994
dtype: int64

In [6]:
Orders[Orders['Postal Code'].isna()].index

Index([173, 710, 1732, 3408, 3409, 4279, 4694, 5490, 7802, 8415, 9693], dtype='int64')

In [7]:
Orders[Orders['Postal Code'].isna()]

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
173,2235,CA-2020-104066,2020-12-05,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10001013,205.03,7,0.0,67.6599
710,9147,US-2019-165505,2019-01-23,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10002926,99.98,2,0.0,42.9914
1732,9389,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Mega Protein,OFF-AP-10000828,542.94,3,0.0,152.0232
3408,9387,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10000157,79.92,4,0.0,37.5624
3409,9388,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10001970,12.28,1,0.0,5.7716
4279,8799,US-2019-150140,2019-04-06,Standard Class,VM-21685,Valerie Mitchum,Facebook,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Only Oats,TEC-PH-10002555,1294.75,5,0.0,336.6350
4694,9390,US-2020-127292,2020-01-19,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Power Clean Fibre Boost,OFF-EN-10001509,2.04,1,0.0,0.9588
5490,9149,US-2019-165505,2019-01-23,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Steel Cut,OFF-ST-10001526,1564.29,13,0.0,406.7154
7802,9148,US-2019-165505,2019-01-23,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Super Mega Protein,OFF-AR-10003477,8.04,6,0.0,2.7336
8415,9742,CA-2018-117086,2018-11-08,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Fruit,FUR-BO-10004834,4404.90,5,0.0,1013.1270
9693,5275,CA-2018-162887,2018-11-07,Second Class,SV-20785,Stewart Visinsky,Email,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Nuts,FUR-CH-10000595,715.20,3,0.0,178.8000

In [8]:
Orders[Orders['Product ID']=='FUR-BO-10004834']

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
8193,28,US-2018-150630,2018-09-17,Standard Class,TB-21520,Tracy Blumstein,Email,United States,Philadelphia,Pennsylvania,19140.0,East,Toasted Muesli,With Fruit,FUR-BO-10004834,3083.4300,7,0.50,-1665.0522
8201,400,CA-2019-108987,2019-09-08,Second Class,AG-10675,Anna Gayman,Email,United States,Houston,Texas,77036.0,Central,Toasted Muesli,With Fruit,FUR-BO-10004834,2396.2656,4,0.32,-317.1528
8326,5918,US-2018-126977,2018-09-17,Standard Class,PF-19120,Peter Fuller,Email,United States,New York City,New York,10035.0,East,Toasted Muesli,With Fruit,FUR-BO-10004834,4228.7040,6,0.20,158.5764
8369,7815,US-2020-109316,2020-06-08,First Class,MG-17680,Maureen Gastineau,Facebook,United States,Los Angeles,California,90049.0,West,Toasted Muesli,With Fruit,FUR-BO-10004834,1497.6660,2,0.15,140.9568
8415,9742,CA-2018-117086,2018-11-08,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Fruit,FUR-BO-10004834,4404.9000,5,0.00,1013.1270

In [9]:
Orders['Ship Mode'].unique()

<StringArray>
['Second Class', 'First Class', 'Standard Class']
Length: 3, dtype: str

In [10]:
Orders['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
First Class       2081
Second Class      1945
Name: count, dtype: int64

In [11]:
Orders['First_class']= np.where(
    Orders['Ship Mode']=='First Class', 1 , 0)

In [12]:
Orders.head(3)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit,First_class
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741,0
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714,1
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500,0

In [13]:
Orders['First_class'].dtypes

dtype('int64')

In [14]:
Orders['Day_name']=Orders['Order Date'].dt.day_name()

In [15]:
Orders.head(4)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,...,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit,First_class,Day_name
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,...,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741,0,Wednesday
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,...,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714,1,Monday
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,...,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500,0,Thursday
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,...,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.00,2,0.0,3.3000,1,Monday

In [16]:
Orders.tail(5)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,...,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit,First_class,Day_name
9989,9894,US-2019-115441,2019-07-25,Second Class,SH-19975,Sally Hughsby,Sales,United States,Milwaukee,Wisconsin,...,Central,Toasted Muesli,With Nuts,FUR-CH-10004626,403.560,4,0.0,96.8544,0,Thursday
9990,9908,US-2018-129007,2018-09-13,First Class,KD-16615,Ken Dana,Sales,United States,Anaheim,California,...,West,Toasted Muesli,With Nuts,FUR-CH-10000155,717.720,3,0.2,71.7720,1,Thursday
9991,9913,CA-2018-132388,2018-10-10,First Class,KN-16390,Katherine Nockton,Sales,United States,Santa Barbara,California,...,West,Toasted Muesli,With Nuts,FUR-CH-10001714,362.136,3,0.2,-54.3204,1,Wednesday
9992,9920,CA-2019-149272,2019-03-15,Standard Class,MY-18295,Muhammed Yedwab,Sales,United States,Bryan,Texas,...,Central,Toasted Muesli,With Nuts,FUR-CH-10000863,528.430,5,0.3,-143.4310,0,Friday
9993,9948,CA-2020-121559,2020-06-01,Second Class,HW-14935,Helen Wasserman,Sales,United States,Indianapolis,Indiana,...,Central,Toasted Muesli,With Nuts,FUR-CH-10003746,1925.880,6,0.0,539.2464,0,Monday

In [20]:
Clean_Orders_table.to_xlsx('../data/cleaned/Clean_Orders_table.xlsx')

NameError: name 'Clean_Orders_table' is not defined