In [10]:
import pandas as pd
import numpy as np

In [21]:
Clean_Orders_table = pd.read_excel("../data/cleaned/Clean_Orders_table.xlsx")

In [22]:
Clean_Orders_table.head(5)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,...,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit,First_class,Day_name
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,...,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741,0,Wednesday
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,...,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714,1,Monday
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,...,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500,0,Thursday
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,...,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.00,2,0.0,3.3000,1,Monday
4,63,CA-2018-135545,2018-11-24,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,...,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0.0,6.1512,0,Saturday

In [13]:
clean_campaign_data = pd.read_excel('../data/cleaned/clean_campaign_data.xlsx')

In [14]:
clean_campaign_data.head(5)

         Order ID Arrival Scan Date     Customer Name
0  CA-2019-109666        2019-05-03      Kunst Miller
1  CA-2019-138933        2019-05-03       Jack Lebron
2  CA-2019-130001        2019-05-03  Heather Kirkland
3  CA-2019-113061        2019-05-06         Ed Ludwig
4  CA-2019-162138        2019-05-06       Grace Kelly

In [17]:
Clean_order_process_data=pd.read_excel('../data/cleaned/Clean_order_process_data.xlsx')

In [18]:
Clean_order_process_data.head(5)

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode,First_class,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate
0,3074,CA-2019-125206,2019-01-03,2019-01-07,Express,1,Monday,4
1,4919,CA-2019-160304,2019-01-02,2019-01-09,Standard Processing,0,Wednesday,7
2,4920,CA-2019-160304,2019-01-02,2019-01-09,Standard Processing,0,Wednesday,7
3,8604,US-2019-116365,2019-01-03,2019-01-09,Standard Processing,0,Wednesday,6
4,8605,US-2019-116365,2019-01-03,2019-01-09,Standard Processing,0,Wednesday,6

In [19]:
Clean_InternData_study=pd.read_excel('../data/cleaned/Clean_InternData_study.xlsx')

In [20]:
Clean_InternData_study.head(5)

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03
2  CA-2019-129847         2019-09-04  2019-09-04
3  CA-2019-129630         2019-09-04  2019-09-04
4  CA-2019-106278         2019-09-05  2019-09-06

In [30]:
merge_orders_process_data = pd.merge( Clean_Orders_table, Clean_order_process_data , on= ['Order ID', 'Order Date','First_class'], how = "left")

In [31]:
merge_orders_process_data.head(5)

,Index,Order ID,Order Date,Ship Mode_x,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,...,Quantity,Discount,Profit,First_class,Day_name,Row ID,On Truck Scan Date,Ship Mode_y,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,...,3,0.0,11.7741,0,Wednesday,26.0,2019-01-23,Standard Processing,Wednesday,7.0
1,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,...,3,0.0,11.7741,0,Wednesday,27.0,2019-01-23,Standard Processing,Wednesday,7.0
2,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,...,2,0.0,19.7714,1,Monday,45.0,2019-03-13,Express,Wednesday,2.0
3,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,...,2,0.0,19.7714,1,Monday,46.0,2019-03-13,Express,Wednesday,2.0
4,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,...,3,0.0,4.9500,0,Thursday,48.0,2019-06-26,Standard Processing,Wednesday,6.0

In [32]:
merge_orders_process_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 21620 entries, 0 to 21619
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Index                           21620 non-null  int64
 1   Order ID                        21620 non-null  str
 2   Order Date                      21620 non-null  datetime64[us]
 3   Ship Mode_x                     21620 non-null  str
 4   Customer ID                     21620 non-null  str
 5   Customer Name                   21620 non-null  str
 6   Origin Channel                  21620 non-null  str
 7   Country/Region                  21620 non-null  str
 8   City                            21620 non-null  str
 9   State                           21620 non-null  str
 10  Postal Code                     21591 non-null  float64
 11  Region                          21620 non-null  str
 12  Category                        21620 non-null  str
 13  Sub-Category                    21620 non-null  str
 14  Product ID                      21620 non-null  str
 15  Sales                           21620 non-null  float64
 16  Quantity                        21620 non-null  int64
 17  Discount                        21620 non-null  float64
 18  Profit                          21620 non-null  float64
 19  First_class                     21620 non-null  int64
 20  Day_name                        21620 non-null  str
 21  Row ID                          17525 non-null  float64
 22  On Truck Scan Date              17525 non-null  datetime64[us]
 23  Ship Mode_y                     17525 non-null  str
 24  Day_name_On_Truck_scan          17525 non-null  str
 25  Diff_OrderDate_OnTruckScanDate  17525 non-null  float64
dtypes: datetime64[us](2), float64(6), int64(3), str(15)
memory usage: 4.3 MB

In [34]:
merge_orders_process_data.duplicated().sum()

np.int64(0)

In [35]:
merge_orders_process_data.columns

Index(['Index', 'Order ID', 'Order Date', 'Ship Mode_x', 'Customer ID',
       'Customer Name', 'Origin Channel', 'Country/Region', 'City', 'State',
       'Postal Code', 'Region', 'Category', 'Sub-Category', 'Product ID',
       'Sales', 'Quantity', 'Discount', 'Profit', 'First_class', 'Day_name',
       'Row ID', 'On Truck Scan Date', 'Ship Mode_y', 'Day_name_On_Truck_scan',
       'Diff_OrderDate_OnTruckScanDate'],
      dtype='str')

In [36]:
date_table = merge_orders_process_data[['Order ID', 'Order Date','First_class', 'Day_name', 'On Truck Scan Date', 'Day_name_On_Truck_scan',
       'Diff_OrderDate_OnTruckScanDate']]

In [37]:
date_table

,Order ID,Order Date,First_class,Day_name,On Truck Scan Date,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate
0,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0
1,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0
2,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0
3,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0
4,CA-2019-169194,2019-06-20,0,Thursday,2019-06-26,Wednesday,6.0
...,...,...,...,...,...,...,...
21615,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0
21616,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0
21617,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0
21618,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0
21619,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0

In [38]:
Merge_date = pd.merge( date_table, Clean_InternData_study , on= ['Order ID'], how = "left")

In [39]:
Merge_date.head(5)

,Order ID,Order Date,First_class,Day_name,On Truck Scan Date,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate,Ready to Ship Date,Pickup Date
0,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0,NaT,NaT
1,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0,NaT,NaT
2,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0,NaT,NaT
3,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0,NaT,NaT
4,CA-2019-169194,2019-06-20,0,Thursday,2019-06-26,Wednesday,6.0,NaT,NaT

In [40]:
Merge_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 23171 entries, 0 to 23170
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Order ID                        23171 non-null  str
 1   Order Date                      23171 non-null  datetime64[us]
 2   First_class                     23171 non-null  int64
 3   Day_name                        23171 non-null  str
 4   On Truck Scan Date              19076 non-null  datetime64[us]
 5   Day_name_On_Truck_scan          19076 non-null  str
 6   Diff_OrderDate_OnTruckScanDate  19076 non-null  float64
 7   Ready to Ship Date              2771 non-null   datetime64[us]
 8   Pickup Date                     2771 non-null   datetime64[us]
dtypes: datetime64[us](4), float64(1), int64(1), str(3)
memory usage: 1.6 MB

In [42]:
Merge_date['processing_time'] = (Merge_date['Ready to Ship Date'] - Merge_date['Order Date']).dt.days

In [43]:
Merge_date['waiting_time'] = (Merge_date['Pickup Date'] - Merge_date['Ready to Ship Date']).dt.days

In [44]:
Merge_date.head(5)

,Order ID,Order Date,First_class,Day_name,On Truck Scan Date,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate,Ready to Ship Date,Pickup Date,processing_time,waiting_time
0,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0,NaT,NaT,NaN,NaN
1,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0,NaT,NaT,NaN,NaN
2,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0,NaT,NaT,NaN,NaN
3,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0,NaT,NaT,NaN,NaN
4,CA-2019-169194,2019-06-20,0,Thursday,2019-06-26,Wednesday,6.0,NaT,NaT,NaN,NaN

In [45]:
Merge_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 23171 entries, 0 to 23170
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Order ID                        23171 non-null  str
 1   Order Date                      23171 non-null  datetime64[us]
 2   First_class                     23171 non-null  int64
 3   Day_name                        23171 non-null  str
 4   On Truck Scan Date              19076 non-null  datetime64[us]
 5   Day_name_On_Truck_scan          19076 non-null  str
 6   Diff_OrderDate_OnTruckScanDate  19076 non-null  float64
 7   Ready to Ship Date              2771 non-null   datetime64[us]
 8   Pickup Date                     2771 non-null   datetime64[us]
 9   processing_time                 2771 non-null   float64
 10  waiting_time                    2771 non-null   float64
dtypes: datetime64[us](4), float64(3), int64(1), str(3)
memory usage: 1.9 MB

In [46]:
def next_monday(date):
    return date + pd.Timedelta(days=(7 - date.weekday()))

def add_processing_time(order_date):
    if order_date.weekday() >= 5:  # weekend
        start = next_monday(order_date)
    else:
        start = order_date
    return start + pd.Timedelta(days=2)

In [47]:
def next_truck_day(date):
    weekday = date.weekday()
    
    if weekday in [0, 2, 4]:  # Mon, Wed, Fri
        return date
    elif weekday == 1:  # Tue → Wed
        return date + pd.Timedelta(days=1)
    elif weekday == 3:  # Thu → Fri
        return date + pd.Timedelta(days=1)
    elif weekday == 5:  # Sat → Mon
        return date + pd.Timedelta(days=2)
    elif weekday == 6:  # Sun → Mon
        return date + pd.Timedelta(days=1)

In [48]:
def calculate_delivery(row):
    
    # Step 1: Ready to ship
    ready_date = add_processing_time(row['Order Date'])
    
    # Step 2: Express (First_class == 1)
    if row['First_class'] == 1:
        ship_date = ready_date
    
    else:
        # wait 1 day
        ship_date = ready_date + pd.Timedelta(days=1)
        
        # move to next truck day
        ship_date = next_truck_day(ship_date)
    
    # Step 3: Delivery (same day)
    return ship_date

In [49]:
Merge_date['delivery_date'] = Merge_date.apply(calculate_delivery, axis=1)

In [50]:
Merge_date.head(10)

,Order ID,Order Date,First_class,Day_name,On Truck Scan Date,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate,Ready to Ship Date,Pickup Date,processing_time,waiting_time,delivery_date
0,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0,NaT,NaT,NaN,NaN,2019-01-21
1,CA-2019-121755,2019-01-16,0,Wednesday,2019-01-23,Wednesday,7.0,NaT,NaT,NaN,NaN,2019-01-21
2,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0,NaT,NaT,NaN,NaN,2019-03-13
3,CA-2019-118255,2019-03-11,1,Monday,2019-03-13,Wednesday,2.0,NaT,NaT,NaN,NaN,2019-03-13
4,CA-2019-169194,2019-06-20,0,Thursday,2019-06-26,Wednesday,6.0,NaT,NaT,NaN,NaN,2019-06-24
5,CA-2019-169194,2019-06-20,0,Thursday,2019-06-26,Wednesday,6.0,NaT,NaT,NaN,NaN,2019-06-24
6,CA-2019-111682,2019-06-17,1,Monday,2019-06-19,Wednesday,2.0,NaT,NaT,NaN,NaN,2019-06-19
7,CA-2019-111682,2019-06-17,1,Monday,2019-06-19,Wednesday,2.0,NaT,NaT,NaN,NaN,2019-06-19
8,CA-2019-111682,2019-06-17,1,Monday,2019-06-19,Wednesday,2.0,NaT,NaT,NaN,NaN,2019-06-19
9,CA-2019-111682,2019-06-17,1,Monday,2019-06-19,Wednesday,2.0,NaT,NaT,NaN,NaN,2019-06-19

In [51]:
Merge_date['shipping_time'] = (Merge_date['delivery_date'] - Merge_date['Pickup Date']).dt.days

In [52]:
Merge_date['total_delivery_time'] = (Merge_date['delivery_date'] - Merge_date['Order Date']).dt.days

In [53]:
Merge_date.tail()

,Order ID,Order Date,First_class,Day_name,On Truck Scan Date,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate,Ready to Ship Date,Pickup Date,processing_time,waiting_time,delivery_date,shipping_time,total_delivery_time
23166,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0,NaT,NaT,NaN,NaN,2020-06-05,NaN,4
23167,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0,NaT,NaT,NaN,NaN,2020-06-05,NaN,4
23168,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0,NaT,NaT,NaN,NaN,2020-06-05,NaN,4
23169,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0,NaT,NaT,NaN,NaN,2020-06-05,NaN,4
23170,CA-2020-121559,2020-06-01,0,Monday,2020-06-05,Friday,4.0,NaT,NaT,NaN,NaN,2020-06-05,NaN,4

In [54]:
Merge_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 23171 entries, 0 to 23170
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Order ID                        23171 non-null  str
 1   Order Date                      23171 non-null  datetime64[us]
 2   First_class                     23171 non-null  int64
 3   Day_name                        23171 non-null  str
 4   On Truck Scan Date              19076 non-null  datetime64[us]
 5   Day_name_On_Truck_scan          19076 non-null  str
 6   Diff_OrderDate_OnTruckScanDate  19076 non-null  float64
 7   Ready to Ship Date              2771 non-null   datetime64[us]
 8   Pickup Date                     2771 non-null   datetime64[us]
 9   processing_time                 2771 non-null   float64
 10  waiting_time                    2771 non-null   float64
 11  delivery_date                   23171 non-null  datetime64[us]
 12  shipping_time                   2771 non-null   float64
 13  total_delivery_time             23171 non-null  int64
dtypes: datetime64[us](5), float64(4), int64(2), str(3)
memory usage: 2.5 MB

In [55]:
Merge_date.to_excel("../data/final/final_data.xlsx", index=False)